import Head from "next/head";
import { Provider, defaultTheme } from "@adobe/react-spectrum";

import styles from "@/styles/Home.module.scss";
import AsyncSortTable from "@/components/Table";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider theme={defaultTheme}>
        <main className={styles.main}>
          <AsyncSortTable />
        </main>
      </Provider>
    </>
  );
}
